### ISSUE TITLE
如何更新邀请码页面的状态颜色~？

### ISSUE THREAD

**Issue by liuchao0130** [xuanhuan/ss-panel#51]
请问下这个状态颜色哪里调呀， 我把背景换成了黑色，格格不入， 我想换个颜色，找了好久

![qq 20150924111028](https://cloud.githubusercontent.com/assets/13215589/10064654/5d8f135e-62ad-11e5-88a3-bedabcdee9c0.png)

**Comment by xuanhuan** [comment]
``` css
/* 彩色表格 */
table {
    background-image: linear-gradient(-45deg, rgba(208, 14, 114, 0.56), yellow);
}
```

https://github.com/xuanhuan/ss-panel/blob/smarty/templates/materialize/asset/css/main.css
